### PR TITLE
Fix instal deps

### PR DESCRIPTION
**Pull request by stuartskelton**
Updated the Makefile.PL to include a missing dependency found in the `bin/chronicle`.

Also removed `Data::Dumper` from the trunctaedbody plugin

### CODE REVIEW

**Comment by stuartskelton** [comment]
File::ShareDir::Install does not list File::ShareDir as a dependency so when I do say a 'CPAN::Minus' install its not installed automagically.

**Comment by skx** [comment]
> File::ShareDir::Install does not list File::ShareDir as a dependency

To me that sounds like the _real_ bug.  I might be missing something though.

**Comment by stuartskelton** [comment]
Also I think File::ShareDIr should be in the PREREQ_PM  as  libfile-sharedir-perl is listed as a dependency of libchronicle-perl.

Too be honest its your decision, I am really just a Perl hacker.

**Comment by skx** [comment]
I will add it - I've just been fighting with myself which isn't so useful.

Thank you for your patience, and for reporting it :)

**Pull request closed without merging**
