### PR TITLE
Safety net for post title collisions

### PR DESCRIPTION
**Pull request by mbethke**
I ran into a problem when I posted a blog entry with a title in Lao script:
http://blog.towiski.de/____.html
As you can see from the URL already, all non-ASCII characters simply get replaced by underscores, which will screw up once you have a second page with a title of equal length in any other non-ASCII script.

A temporary safety net against chronicle simply overwriting one article with the other is to create a unique index on the blog table's title column, so it will just fail with a cryptic error (it would be useful to dump the attempted query and error code if any SQL fails, too). Of course it would be preferable to have this Just Work[tm] but I'm not sure yet how to do it. I wrote some code to keep `$entry->{link}` in URL-encoded form using `URL::Encode` (without stripping on-ASCII characters first) and then to decode it again for actual file name creation, but this still doesn't work for non-Latin scripts, probably everything but ISO-Latin-1.

The important bit is the second commit, you may not like the first one though ;)

### CODE REVIEW

**Comment by skx** [comment]
Even without looking at the code I know this is a valid bug, it has crossed my mind in the past that this non-ASCII replacements would cause problems for people who use foreign character-sets.

I'm happy to accept the second & third patches.  The first one is a massive amount of churn for little gain - I don't see complaints from `perlcritic`, or `perltidy`, etc, so I'm loathe to apply it just for the sake of stylistic preferences.

If you could drop references then I'll merge the pull request.  If you can't revert that part of the PR I'll apply manually and commit.  Just let me know which I should do - wait or apply manually.

Thanks for your contribution!

**Comment by mbethke** [comment]
I think merging manually is the better option -- I could try some git rebase trickery to make the first commit go away but I don't have much experience with that and would probably complicate it even more :)
Hopefully I can get something more useful working these days.

**Comment by skx** [comment]
Thanks for the update.  It is late here now, but I'll patchup and close tomorrow.

Thanks again for your contribution :)

**Comment by mbethke** [comment]
You're very welcome -- and thanks for creating this useful tool! I've been a big fan of generated static sites ever since I started using HSC (later maintaining it too, http://towiski.de/software.html#HSC) but its macro language has started to smell too much of the 90s for it to be a good candidate for writing my blog :)

**Comment by skx** [comment]
https://github.com/skx/chronicle2/commit/c262fb6454ab1c3c2091ae107bec9483f3b56791

**Pull request closed without merging**
