### PR TITLE
Allow for the user to choose the min and max sizes for their tag cloud

### PR DESCRIPTION
**Pull request by stuartskelton**
This allows for a user to choose their min and max size of their tag cloud, We could also change the step size from 5 also but I am not sure the usefulness of this. Unless someone sets a low min and max, only yo find out they have a lot fewer steps.

Thinking about it, We could add code that a user could specify how many steps they want and the code will set up the boundaries within their limits.

### CODE REVIEW

**Comment by stuartskelton** [comment]
I thought  `Plugins/Snippets/Meta.pm` was concerned with populating  `$Chronicle::GLOBAL_TEMPLATE_VARS`,  so data was available within the templates. 

However because of the need of this data to be within the config because `Chronicle::Plugin::Generate::Tags` needs the information and not the template file.

ps I will also have to edit `Chronicle::Plugin::Snippets::AllTags` with the same code.

**Comment by skx** [comment]
I was using that as an example of a plugin which uses a local-config option.  Rather than because the functionality is the same :)

i.e. The main script doesn't need to have a config-option for the date-format, and neither does it for the tag-sizes.

I'm happy enough for the code to be duplicated, but the config-fetching shoudln't happen in `bin/chronicle2`, it should be local to the two plugins that use it.

**Comment by stuartskelton** [comment]
ahh I think I have worked it out

**Comment by stuartskelton** [comment]
if you think that will be good ill copy it to the other plugin, then we can close this

**Comment by skx** [comment]
> if you think that will be good ill copy it to the other plugin, then we can close this

Yup, I think that's good now.    If you update the other plugin too I'll merge and close.

Thanks for your continued patience and contributions :)

**Comment by stuartskelton** [comment]
No Worries.

**Pull request merged**
